name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
    build:
      runs-on: ubuntu-latest
      outputs:     
        file: ${{ steps.file_name.outputs.res }} 

      steps:
      - id: file_name
        run: |
          touch new1
          echo "res=$( [ -f "new1" ] && echo "true" || echo "false" )" >> $GITHUB_OUTPUT
      - name: print res    
        run: echo ${{ steps.file_name.outputs.res }} 

      - name: file contents
        run: echo "Hello World" > $new1

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: my-artifact                
          path: ./new1  

    publish:
      runs-on: ubuntu-latest
      needs: build

      steps:
        - name: Download artifact
          uses: actions/download-artifact@v4
          with:
            name: my-artifact 

        - name: Print Contents
          run: car $new1
