name: CI
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
    job1:
      runs-on: ubuntu-latest
      # Map a step output to a job output
      outputs:
        output1: ${{ steps.step1.outputs.test1 }}       # steps.<setp_id>.outputs.<variable_name>
        output2: ${{ steps.step2.outputs.test2 }}       
      steps:
      - id: step1                                       # step1 is the setp id
        run: echo "test1=hello" >> $GITHUB_OUTPUT       # test1 is the variable name
      - id: step2                                       # step2 is the setp id
        run: echo "test2=world" >> $GITHUB_OUTPUT       # test2 is the variable name
      - name: print
        run: echo ${{ steps.step1.outputs.test1 }} ${{ steps.step2.outputs.test2 }} 
      - id: step3
        run: |
          touch new1
          res=$( [ -d "new1" ] && echo "true" || echo "false" ) >> $GITHUB_OUTPUT
          echo ${{ steps.step3.outputs.res }} 
    job2:
      runs-on: ubuntu-latest
      needs: job1
      steps:
      - run: echo ${{needs.job1.outputs.output1}} ${{needs.job1.outputs.output2}}
